path:
  # Path to output data - refer to as $data in entries below. This data
  # directory lives in the root directory given below (most likely where this
  # config file lives as well).
  data: data/
  fig: fig/

# Input and output data
data:
  proc:
    # Processed adcp data. Link or copy processed netcdf files into this directory.
    adcp: $data/proc/adcp/
    mb: $data/proc/mb/merged_100_-28_-21_56_61.nc

  gridded:
    adcp: $data/gridded/adcp/

  ssh: $data/ssh/
  wind:
    dir: $data/wind/
    era5: $data/wind/era5_uv_10m.nc 

mooring_locations: $data/niskine_mooring_locations.nc
